param([Parameter(Mandatory=$true)][ValidateSet('load','reload','errors','remove')][string]$Operation,[string]$ExtensionId,[string]$Path)
$ErrorActionPreference='Stop'
if($PSVersionTable.PSVersion.Major -lt 7){throw 'Chrome Ops helper requires PowerShell 7+'}
[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new($false)
Add-Type -AssemblyName UIAutomationClient
Add-Type -AssemblyName UIAutomationTypes
$JExt='拡張機能'; $JBack='戻る'; $JLoad='パッケージ化されていない拡張機能を読み込む'
$JFolder='フォルダー'; $JChoose='フォルダーの選択'; $JReload='再読み込み'; $JErrors='エラー'; $JRemove='削除'
function Result($ok,$data=$null,$error=$null){[pscustomobject]@{ok=$ok;operation="extension.dev.$Operation";data=$data;error=$error}|ConvertTo-Json -Depth 8 -Compress}
function Desc($r){$r.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition)}
function ChromeWindow{$root=[System.Windows.Automation.AutomationElement]::RootElement;foreach($w in $root.FindAll([System.Windows.Automation.TreeScope]::Children,[System.Windows.Automation.Condition]::TrueCondition)){if($w.Current.ClassName -eq 'Chrome_WidgetWin_1' -and $w.Current.Name -match "^($JExt|Extensions)"){return $w}};throw 'chrome://extensions must be open in a Chrome window'}
function InvokeNamed($r,[string]$name){foreach($e in (Desc $r)){if($e.Current.Name -eq $name){try{$e.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke();return $true}catch{}}};return $false}
try{
  $w=ChromeWindow
  if($Operation -eq 'load'){
    if(-not $Path){throw 'Path is required'};$resolved=(Resolve-Path -LiteralPath $Path).Path;if(-not(Test-Path -LiteralPath(Join-Path $resolved 'manifest.json') -PathType Leaf)){throw 'manifest.json not found'}
    $root=[System.Windows.Automation.AutomationElement]::RootElement;$before=@();foreach($x in $root.FindAll([System.Windows.Automation.TreeScope]::Children,[System.Windows.Automation.Condition]::TrueCondition)){if($x.Current.Name -match 'directory' -or $x.Current.ClassName -eq '#32770'){$before+=$x.Current.NativeWindowHandle}}
    if(-not(InvokeNamed $w $JLoad)){if(-not(InvokeNamed $w 'Load unpacked')){throw 'Load unpacked control not found'}};Start-Sleep -Milliseconds 400
    $dialog=$null;foreach($x in $root.FindAll([System.Windows.Automation.TreeScope]::Children,[System.Windows.Automation.Condition]::TrueCondition)){if(($x.Current.Name -match 'directory' -or $x.Current.ClassName -eq '#32770') -and $before -notcontains $x.Current.NativeWindowHandle){$dialog=$x;break}};if(-not$dialog){foreach($x in(Desc $w)){if(($x.Current.Name -match 'directory' -or $x.Current.ClassName -eq '#32770') -and $before -notcontains $x.Current.NativeWindowHandle){$dialog=$x;break}}}
    if(-not $dialog){throw 'Extension directory picker not found'};$edit=$null;$choose=$null;foreach($e in(Desc $dialog)){if($e.Current.ControlType -eq [System.Windows.Automation.ControlType]::Edit -and $e.Current.Name -match "($JFolder|Folder)"){$edit=$e};if($e.Current.ControlType -eq [System.Windows.Automation.ControlType]::Button -and $e.Current.Name -match "($JChoose|Select Folder)"){$choose=$e}}
    if(-not$edit -or -not$choose){throw 'Folder picker controls not found'};$edit.GetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern).SetValue($resolved);$choose.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke();Result $true @{path=$resolved};exit 0
  }
  if(-not$ExtensionId){throw 'ExtensionId is required'};$idText="ID: $ExtensionId";$anchor=$null;foreach($e in(Desc $w)){if($e.Current.Name -eq $idText){$anchor=$e;break}}
  if(-not$anchor){if(InvokeNamed $w $JBack){Start-Sleep -Milliseconds 300}elseif(InvokeNamed $w 'Back'){Start-Sleep -Milliseconds 300};foreach($e in(Desc $w)){if($e.Current.Name -eq $idText){$anchor=$e;break}}}
  if(-not$anchor){throw "Extension id not found: $ExtensionId"};$group=[System.Windows.Automation.TreeWalker]::ControlViewWalker.GetParent($anchor);if(-not$group){throw 'Extensions group not found'};$siblings=@(Desc $group);$start=-1;for($i=0;$i -lt $siblings.Count;$i++){if($siblings[$i].Current.Name -eq $idText){$start=$i;break}};if($start -lt 0){throw 'Extension id sequence not found'};$extensionName=$null;for($i=$start-1;$i -ge 0;$i--){$candidate=$siblings[$i].Current.Name;if($candidate -match '^ID: [a-p]{32}$'){break};if($candidate -and $candidate -notmatch '^\d+\.\d+' -and $candidate -notmatch 'unpacked|package|詳細|削除|再読み込み|Errors|Remove|Reload'){$extensionName=$candidate;break}}
  if($Operation -eq 'remove' -and $extensionName){foreach($x in(Desc $w)){if($x.Current.Name -like "*$extensionName*" -and $x.Current.Name -match '(削除|Remove)'){$dialog=$x;for($d=0;$d -lt 4 -and $dialog;$d++){$buttons=@((Desc $dialog)|Where-Object{$_.Current.ControlType -eq [System.Windows.Automation.ControlType]::Button -and ($_.Current.Name -eq $JRemove -or $_.Current.Name -eq 'Remove')});if($buttons.Count){$buttons[0].GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke();Result $true @{extensionId=$ExtensionId;name=$extensionName;removed=$true};exit 0};$dialog=[System.Windows.Automation.TreeWalker]::ControlViewWalker.GetParent($dialog)}}}}
  $names=@{reload=@($JReload,'Reload');errors=@($JErrors,'Errors');remove=@($JRemove,'Remove')}[$Operation];for($i=$start+1;$i -lt $siblings.Count;$i++){ $e=$siblings[$i];if($e.Current.Name -match '^ID: [a-p]{32}$'){break};if($names -contains $e.Current.Name){try{$e.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke();$n=$e.Current.Name
    if($Operation -eq 'errors'){Start-Sleep -Milliseconds 300;$items=@();foreach($e in(Desc $w)){if($e.Current.ControlType -eq [System.Windows.Automation.ControlType]::Button -and $e.Current.Name -match '(WebSocket|Error|failed|ERR_|TypeError|ReferenceError|SyntaxError)'){$items+= $e.Current.Name}};Result $true @{extensionId=$ExtensionId;control=$Operation;errors=@($items|Select-Object -Unique)};exit 0}
    if($Operation -eq 'remove'){Start-Sleep -Milliseconds 250;$confirm=$null;foreach($x in(Desc $w)){if($extensionName -and $x.Current.Name -like "*$extensionName*" -and $x.Current.Name -match '(削除|Remove)'){$confirm=$x;break}};if(-not$confirm){throw 'Remove confirmation for target extension not found'};for($d=0;$d -lt 4 -and $confirm;$d++){foreach($x in(Desc $confirm)){if($x.Current.ControlType -eq [System.Windows.Automation.ControlType]::Button -and ($x.Current.Name -eq $JRemove -or $x.Current.Name -eq 'Remove')){$x.GetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern).Invoke();Result $true @{extensionId=$ExtensionId;name=$extensionName;removed=$true};exit 0}};$confirm=[System.Windows.Automation.TreeWalker]::ControlViewWalker.GetParent($confirm)};throw 'Remove confirmation button not found'}
    Result $true @{extensionId=$ExtensionId;control=$Operation};exit 0
  }catch{}}};throw "Control not found for $Operation"
}catch{Result $false $null $_.Exception.Message;exit 1}
